name: Validar Shell Script

on:
  push:
    branches: [ "main" ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Ejecutar ShellCheck
        run: shellcheck mi_script.sh
